language: node_js
before_install:
- npm install typescript -g
- npm install browserify -g
node_js:
- node
script: yarn build
deploy:
- provider: npm
  api_key:
    secure: Br3IFmHvWhlLeV51PbD9vh5L/2Jpkm3/oibmJv7R4J/q2SG5gzTXjDNa3bsF7E6Ch/bkqdCBWjd5D2V1wmJF/4GWeRyXu/AOzuy29zUWqx48Fs4tPKM6Wx8iZNI1COLUe+NrdjB+MTET9yKjKY6eozZAB5N4FBwCuoFnT+GhqncrUA3rjzwVy3uPGc4oqhEqE0DKckgo94nngL+DutCRLx2gjPpAjB9WP7kN8XHZfp/qsD9z5pgo04jITAYGX5raRLRriUIkkz9ZzWHmeITLebFpX8Z1vUzg3OJWnAjUjo5mRbngCnsMbEcFkHmj6VskuPHCFe1EAdjn5ACcowd6bxorsi8uRIC01Epty4ZsIliWUSpYhhHiFBOGzyKHrbZLV61srVzsjjDZfHVYt/8vsxjmhwOChSLI+omqDN8T2AoX3lJsI/UdCMEFvis6TgxLVPnaKFjBHg9XwgEyvp33AglBQMKrqEF+Tvw2NhOKDRv7FYlPu+ZXoWrss0L9J5ZINKoNq7/gxhZ4GjjWSWV+ccfJyPQEqIGQVYbmuUDOrs2pdYbqsLSAQA9QfjftMoImvjHN3DUSUXKGt/V4LCqiDU7A3wWuuM79CS+zKOUEzVHnhgT2VkGGnCMttSEKCeB6neW8t/C7YqckjKBBGVAMN5zrc44Cg1VMSVA7KK1KMYg=
  email: "github@dragon-angel.fr"
  skip_cleanup: true
