version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.1.0
    - 9.1.1
  - dependency-name: puppeteer
    versions:
    - 8.0.0
  - dependency-name: source-map-loader
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
  - dependency-name: style-loader
    versions:
    - 2.0.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
  - dependency-name: webpack
    versions:
    - 5.16.0
    - 5.18.0
    - 5.19.0
    - 5.21.2
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@types/assert"
    versions:
    - 1.5.4
  registries:
  - npm-registry-registry-npmjs-org
