// Generated by typings
declare module "sequencify" {


    function sequencify(definitions: sequencify.definition[] | { [name: string]: sequencify.definition }, toOrder: string[], orderedArray: string[]);

    namespace sequencify
    {
        export interface definition
        {
            name: string;
            dep: string[];
        }
    }

    export = sequencify;
}