outputs: $(build.publicPackages)

jobs:
  build:
    steps:
      - name: semantic-release
        outputAs: releases
        job: ./semantic-releases.yml
      - name: versions
        dispatch: get-version
        with:
          path: $($)
        outputAs: versions
        foreach: $(build.releases)
      - name: log versions
        log:
          - "%O"
          - $(build.versions)
      - name: eliminate private packages
        dispatch: eliminate-private
        outputAs: publicPackages
        with:
          packages: $(build.releases)
      - name: push1
        run: git push
        with:
          shell: true
      - name: tag
        foreach: $(build.publicPackages)
        foreach-strategy: wait-for-previous
        run:
          - git
          - tag
          - -a
          - $($.name)@$($.version)
          - -m
          - tagging $($.name)@$($.version)
      - name: push2
        run: git push origin --tags
        with:
          shell: true
      - name: log all
        log: $(build.publicPackages)
      - name: publish
        foreach: $(build.publicPackages)
        foreach-strategy: wait-for-previous
        run: yarn workspace $($.name) npm publish --access public
        retries: 3
        with:
          shell: true
