jobs:
  build:
    steps:
      - name: workspaces
        run:
          - yarn
          - workspaces
          - list
          - --json
          - --verbose
        with:
          result: stdout
          format: jsonnd
      - name: use self
        uses: ./commands.json
      - name: semantic-release
        outputAs: versions
        foreach: $(build.workspaces)
        job: ./semantic-release.yml
        with:
          package: $($)
          changelogPath: $($.location)/changelog.md
      - name: bumpDependents
        dispatch: bump-dependents
        outputAs: bumps
        with:
          workspaces: $(build.workspaces)
          versions: $(build.versions)
          strategy:
            major: patch
            minor: patch
            patch: patch
          changelog: changelog.md
      - name: bump
        foreach: $(build.bumps)
        foreach-strategy: wait-for-previous
        run: |
          yarn workspace $($.name) version $($.bump)
          git add $($.location)/package.json
          git add $($.location)/changelog.md
          git commit -m "bumping $($.name)"
        with:
          shell: true
          ignore-failure: true
