export * from './model/command'
export * from './model/container'
export * from './decorators'
export * from './generator'
export * from './model/trigger'
export * from './model/processor'
export * from './model/error-unknowncommand'
import * as Processors from './processors'
import * as Triggers from './triggers'
import * as Metadata from './metadata'
import serveMetadata, { ServeMetadata } from './serve-metadata'
// import * as cli from './cli'
export { Processors, Triggers, Metadata }
export { NetSocketAdapter, default as serve, ServeOptions } from './cli/serve'
export { serveMetadata, ServeMetadata };