export type JsonSchema = {
    "$id"?: string,
    "$schema"?: string,
    "$ref"?: string,
    "$comment"?: string,
    "title"?: string,
    "description"?: string,
    "default"?: unknown,
    "readOnly"?: boolean,
    "writeOnly"?: boolean,
    "examples"?: [...(unknown)[]],
    "multipleOf"?: number,
    "maximum"?: number,
    "exclusiveMaximum"?: number,
    "minimum"?: number,
    "exclusiveMinimum"?: number,
    "maxLength"?: number,
    "minLength"?: (number) & (unknown),
    "pattern"?: string,
    "additionalItems"?: JsonSchema,
    "items"?: (JsonSchema) | ([...(JsonSchema)[]]),
    "maxItems"?: number,
    "minItems"?: (number) & (unknown),
    "uniqueItems"?: boolean,
    "contains"?: JsonSchema,
    "maxProperties"?: number,
    "minProperties"?: (number) & (unknown),
    "required"?: [...(string)[]],
    "additionalProperties"?: JsonSchema | false,
    "properties"?: JsonSchema,
    "patternProperties"?: Record<string, JsonSchema>;
    "dependencies"?: (JsonSchema) | ([...(string)[]]),
    "propertyNames"?: JsonSchema,
    "const"?: unknown,
    "enum"?: [...(unknown)[]],
    "type"?: ("array" | "boolean" | "integer" | "null" | "number" | "object" | "string") | ([...("array" | "boolean" | "integer" | "null" | "number" | "object" | "string")[]]),
    "format"?: string,
    "contentMediaType"?: string,
    "contentEncoding"?: string,
    "if"?: JsonSchema,
    "then"?: JsonSchema,
    "else"?: JsonSchema,
    "allOf"?: [...(JsonSchema)[]],
    "anyOf"?: [...(JsonSchema)[]],
    "oneOf"?: [...(JsonSchema)[]],
    "not"?: JsonSchema
    "$defs"?: JsonSchema
};
