//eslint-disable-next-line @typescript-eslint/ban-ts-comment
//@ts-ignore 6133
//eslint-disable-next-line @typescript-eslint/no-unused-vars
import {Arguments, Argument0, Argument1, Argument2, Argument3, Argument4, Argument5, Argument6, Argument7, Argument8, Argument9, Argument10, Argument11, Argument12, Argument13, Argument14, Argument15, Argument16, Argument17 } from '@akala/core';
// eslint-disable-next-line @typescript-eslint/no-namespace
namespace commands
{
	export interface container 
	{
		dispatch (cmd:'$disconnect', ...args: [Argument0<typeof import('./server/commands/$disconnect.js').default>]): ReturnType<typeof import('./server/commands/$disconnect.js').default>
		dispatch (cmd:'$init', ...args: [Argument1<typeof import('./server/commands/$init.js').default>, Argument2<typeof import('./server/commands/$init.js').default>, Argument3<typeof import('./server/commands/$init.js').default>]): ReturnType<typeof import('./server/commands/$init.js').default>
		dispatch (cmd:'$request', ...args: [Argument0<typeof import('./server/commands/$request.js').default>, Argument1<typeof import('./server/commands/$request.js').default>]): ReturnType<typeof import('./server/commands/$request.js').default>
		dispatch (cmd:'add-token', ...args: [Argument0<typeof import('./server/commands/add-token.js').default>, Argument1<typeof import('./server/commands/add-token.js').default>, Argument2<typeof import('./server/commands/add-token.js').default>, Argument3<typeof import('./server/commands/add-token.js').default>]): ReturnType<typeof import('./server/commands/add-token.js').default>
		dispatch (cmd:'client.add', ...args: [Argument0<typeof import('./server/commands/client/add.js').default>, Argument1<typeof import('./server/commands/client/add.js').default>, Argument2<typeof import('./server/commands/client/add.js').default>, Argument3<typeof import('./server/commands/client/add.js').default>, Argument4<typeof import('./server/commands/client/add.js').default>]): ReturnType<typeof import('./server/commands/client/add.js').default>
		dispatch (cmd:'client.delete', ...args: [Argument0<typeof import('./server/commands/client/delete.js').default>]): ReturnType<typeof import('./server/commands/client/delete.js').default>
		dispatch (cmd:'client.renew-secret', ...args: [Argument0<typeof import('./server/commands/client/renew-secret.js').default>, Argument1<typeof import('./server/commands/client/renew-secret.js').default>]): ReturnType<typeof import('./server/commands/client/renew-secret.js').default>
		dispatch (cmd:'client.request-grant', ...args: [Argument0<typeof import('./server/commands/client/request-grant.js').default>, Argument1<typeof import('./server/commands/client/request-grant.js').default>, Argument2<typeof import('./server/commands/client/request-grant.js').default>, Argument3<typeof import('./server/commands/client/request-grant.js').default>, Argument4<typeof import('./server/commands/client/request-grant.js').default>]): ReturnType<typeof import('./server/commands/client/request-grant.js').default>
		dispatch (cmd:'client.update', ...args: [Argument0<typeof import('./server/commands/client/update.js').default>, Argument1<typeof import('./server/commands/client/update.js').default>]): ReturnType<typeof import('./server/commands/client/update.js').default>
		dispatch (cmd:'extend-token', ...args: [Argument0<typeof import('./server/commands/extend-token.js').default>, Argument1<typeof import('./server/commands/extend-token.js').default>]): ReturnType<typeof import('./server/commands/extend-token.js').default>
		dispatch (cmd:'get-oidc-configuration', ...args: [Argument0<typeof import('./server/commands/get-oidc-configuration.js').default>]): ReturnType<typeof import('./server/commands/get-oidc-configuration.js').default>
		dispatch (cmd:'getJWT', ...args: [Argument0<typeof import('./server/commands/getJWT.js').default>, Argument1<typeof import('./server/commands/getJWT.js').default>, Argument2<typeof import('./server/commands/getJWT.js').default>, Argument3<typeof import('./server/commands/getJWT.js').default>, Argument4<typeof import('./server/commands/getJWT.js').default>]): ReturnType<typeof import('./server/commands/getJWT.js').default>
		dispatch (cmd:'login', ...args: [Argument0<typeof import('./server/commands/login.js').default>, Argument1<typeof import('./server/commands/login.js').default>, Argument2<typeof import('./server/commands/login.js').default>]): ReturnType<typeof import('./server/commands/login.js').default>
		dispatch (cmd:'remove-token', ...args: [Argument0<typeof import('./server/commands/remove-token.js').default>]): ReturnType<typeof import('./server/commands/remove-token.js').default>
		dispatch (cmd:'session.add-session', ...args: [Argument0<typeof import('./server/commands/session/add-session.js').default>, Argument1<typeof import('./server/commands/session/add-session.js').default>, Argument2<typeof import('./server/commands/session/add-session.js').default>, Argument3<typeof import('./server/commands/session/add-session.js').default>, Argument4<typeof import('./server/commands/session/add-session.js').default>]): ReturnType<typeof import('./server/commands/session/add-session.js').default>
		dispatch (cmd:'session.extend-session', ...args: [Argument0<typeof import('./server/commands/session/extend-session.js').default>, Argument1<typeof import('./server/commands/session/extend-session.js').default>]): ReturnType<typeof import('./server/commands/session/extend-session.js').default>
		dispatch (cmd:'session.remove-session', ...args: [Argument0<typeof import('./server/commands/session/remove-session.js').default>]): ReturnType<typeof import('./server/commands/session/remove-session.js').default>
		dispatch (cmd:'user.add-user', ...args: [Argument0<typeof import('./server/commands/user/add-user.js').default>, Argument1<typeof import('./server/commands/user/add-user.js').default>]): ReturnType<typeof import('./server/commands/user/add-user.js').default>
		dispatch (cmd:'user.change-password', ...args: [Argument0<typeof import('./server/commands/user/change-password.js').default>, Argument1<typeof import('./server/commands/user/change-password.js').default>, Argument2<typeof import('./server/commands/user/change-password.js').default>]): ReturnType<typeof import('./server/commands/user/change-password.js').default>
		dispatch (cmd:'user.disable-user', ...args: [Argument0<typeof import('./server/commands/user/disable-user.js').default>]): ReturnType<typeof import('./server/commands/user/disable-user.js').default>
		dispatch (cmd:'user.enable-user', ...args: [Argument0<typeof import('./server/commands/user/enable-user.js').default>]): ReturnType<typeof import('./server/commands/user/enable-user.js').default>
		dispatch (cmd:'user.remove-user', ...args: [Argument0<typeof import('./server/commands/user/remove-user.js').default>]): ReturnType<typeof import('./server/commands/user/remove-user.js').default>
		dispatch (cmd:'user.request-reset-password', ...args: [Argument0<typeof import('./server/commands/user/request-reset-password.js').default>]): ReturnType<typeof import('./server/commands/user/request-reset-password.js').default>
		dispatch (cmd:'user.reset-password', ...args: [Argument0<typeof import('./server/commands/user/reset-password.js').default>, Argument1<typeof import('./server/commands/user/reset-password.js').default>, Argument2<typeof import('./server/commands/user/reset-password.js').default>]): ReturnType<typeof import('./server/commands/user/reset-password.js').default>
		dispatch (cmd:'whoami', ...args: []): ReturnType<typeof import('./server/commands/whoami.js').default>
	}
	export interface proxy 
	{
		'$disconnect'(...args: [Argument0<typeof import('./server/commands/$disconnect.js').default>]): ReturnType<typeof import('./server/commands/$disconnect.js').default>
		'$init'(...args: [Argument1<typeof import('./server/commands/$init.js').default>, Argument2<typeof import('./server/commands/$init.js').default>, Argument3<typeof import('./server/commands/$init.js').default>]): ReturnType<typeof import('./server/commands/$init.js').default>
		'$request'(...args: [Argument0<typeof import('./server/commands/$request.js').default>, Argument1<typeof import('./server/commands/$request.js').default>]): ReturnType<typeof import('./server/commands/$request.js').default>
		'add-token'(...args: [Argument0<typeof import('./server/commands/add-token.js').default>, Argument1<typeof import('./server/commands/add-token.js').default>, Argument2<typeof import('./server/commands/add-token.js').default>, Argument3<typeof import('./server/commands/add-token.js').default>]): ReturnType<typeof import('./server/commands/add-token.js').default>
		'client.add'(...args: [Argument0<typeof import('./server/commands/client/add.js').default>, Argument1<typeof import('./server/commands/client/add.js').default>, Argument2<typeof import('./server/commands/client/add.js').default>, Argument3<typeof import('./server/commands/client/add.js').default>, Argument4<typeof import('./server/commands/client/add.js').default>]): ReturnType<typeof import('./server/commands/client/add.js').default>
		'client.delete'(...args: [Argument0<typeof import('./server/commands/client/delete.js').default>]): ReturnType<typeof import('./server/commands/client/delete.js').default>
		'client.renew-secret'(...args: [Argument0<typeof import('./server/commands/client/renew-secret.js').default>, Argument1<typeof import('./server/commands/client/renew-secret.js').default>]): ReturnType<typeof import('./server/commands/client/renew-secret.js').default>
		'client.request-grant'(...args: [Argument0<typeof import('./server/commands/client/request-grant.js').default>, Argument1<typeof import('./server/commands/client/request-grant.js').default>, Argument2<typeof import('./server/commands/client/request-grant.js').default>, Argument3<typeof import('./server/commands/client/request-grant.js').default>, Argument4<typeof import('./server/commands/client/request-grant.js').default>]): ReturnType<typeof import('./server/commands/client/request-grant.js').default>
		'client.update'(...args: [Argument0<typeof import('./server/commands/client/update.js').default>, Argument1<typeof import('./server/commands/client/update.js').default>]): ReturnType<typeof import('./server/commands/client/update.js').default>
		'extend-token'(...args: [Argument0<typeof import('./server/commands/extend-token.js').default>, Argument1<typeof import('./server/commands/extend-token.js').default>]): ReturnType<typeof import('./server/commands/extend-token.js').default>
		'get-oidc-configuration'(...args: [Argument0<typeof import('./server/commands/get-oidc-configuration.js').default>]): ReturnType<typeof import('./server/commands/get-oidc-configuration.js').default>
		'getJWT'(...args: [Argument0<typeof import('./server/commands/getJWT.js').default>, Argument1<typeof import('./server/commands/getJWT.js').default>, Argument2<typeof import('./server/commands/getJWT.js').default>, Argument3<typeof import('./server/commands/getJWT.js').default>, Argument4<typeof import('./server/commands/getJWT.js').default>]): ReturnType<typeof import('./server/commands/getJWT.js').default>
		'login'(...args: [Argument0<typeof import('./server/commands/login.js').default>, Argument1<typeof import('./server/commands/login.js').default>, Argument2<typeof import('./server/commands/login.js').default>]): ReturnType<typeof import('./server/commands/login.js').default>
		'remove-token'(...args: [Argument0<typeof import('./server/commands/remove-token.js').default>]): ReturnType<typeof import('./server/commands/remove-token.js').default>
		'session.add-session'(...args: [Argument0<typeof import('./server/commands/session/add-session.js').default>, Argument1<typeof import('./server/commands/session/add-session.js').default>, Argument2<typeof import('./server/commands/session/add-session.js').default>, Argument3<typeof import('./server/commands/session/add-session.js').default>, Argument4<typeof import('./server/commands/session/add-session.js').default>]): ReturnType<typeof import('./server/commands/session/add-session.js').default>
		'session.extend-session'(...args: [Argument0<typeof import('./server/commands/session/extend-session.js').default>, Argument1<typeof import('./server/commands/session/extend-session.js').default>]): ReturnType<typeof import('./server/commands/session/extend-session.js').default>
		'session.remove-session'(...args: [Argument0<typeof import('./server/commands/session/remove-session.js').default>]): ReturnType<typeof import('./server/commands/session/remove-session.js').default>
		'user.add-user'(...args: [Argument0<typeof import('./server/commands/user/add-user.js').default>, Argument1<typeof import('./server/commands/user/add-user.js').default>]): ReturnType<typeof import('./server/commands/user/add-user.js').default>
		'user.change-password'(...args: [Argument0<typeof import('./server/commands/user/change-password.js').default>, Argument1<typeof import('./server/commands/user/change-password.js').default>, Argument2<typeof import('./server/commands/user/change-password.js').default>]): ReturnType<typeof import('./server/commands/user/change-password.js').default>
		'user.disable-user'(...args: [Argument0<typeof import('./server/commands/user/disable-user.js').default>]): ReturnType<typeof import('./server/commands/user/disable-user.js').default>
		'user.enable-user'(...args: [Argument0<typeof import('./server/commands/user/enable-user.js').default>]): ReturnType<typeof import('./server/commands/user/enable-user.js').default>
		'user.remove-user'(...args: [Argument0<typeof import('./server/commands/user/remove-user.js').default>]): ReturnType<typeof import('./server/commands/user/remove-user.js').default>
		'user.request-reset-password'(...args: [Argument0<typeof import('./server/commands/user/request-reset-password.js').default>]): ReturnType<typeof import('./server/commands/user/request-reset-password.js').default>
		'user.reset-password'(...args: [Argument0<typeof import('./server/commands/user/reset-password.js').default>, Argument1<typeof import('./server/commands/user/reset-password.js').default>, Argument2<typeof import('./server/commands/user/reset-password.js').default>]): ReturnType<typeof import('./server/commands/user/reset-password.js').default>
		'whoami'(...args: []): ReturnType<typeof import('./server/commands/whoami.js').default>
	}
}

export { commands as default };