//eslint-disable-next-line @typescript-eslint/ban-ts-comment
//@ts-ignore 6133
//eslint-disable-next-line @typescript-eslint/no-unused-vars
import {Arguments, Argument0, Argument1, Argument2, Argument3, Argument4, Argument5, Argument6, Argument7, Argument8, Argument9, Argument10, Argument11, Argument12, Argument13, Argument14, Argument15, Argument16, Argument17 } from '@akala/core';
import {Metadata, ICommandProcessor, Container, registerCommands} from "@akala/commands";
// eslint-disable-next-line @typescript-eslint/no-namespace
namespace oidcServer
{
	export interface container 
	{
		dispatch (cmd:'authenticate', ...args: [Argument0<typeof import('./server/oidc-server/authenticate.ts').default>, Argument1<typeof import('./server/oidc-server/authenticate.ts').default>, Argument2<typeof import('./server/oidc-server/authenticate.ts').default>, Argument3<typeof import('./server/oidc-server/authenticate.ts').default>, Argument4<typeof import('./server/oidc-server/authenticate.ts').default>, Argument5<typeof import('./server/oidc-server/authenticate.ts').default>, Argument6<typeof import('./server/oidc-server/authenticate.ts').default>, Argument7<typeof import('./server/oidc-server/authenticate.ts').default>, Argument8<typeof import('./server/oidc-server/authenticate.ts').default>, Argument9<typeof import('./server/oidc-server/authenticate.ts').default>, Argument10<typeof import('./server/oidc-server/authenticate.ts').default>, Argument11<typeof import('./server/oidc-server/authenticate.ts').default>, Argument12<typeof import('./server/oidc-server/authenticate.ts').default>]): ReturnType<typeof import('./server/oidc-server/authenticate.ts').default>
		dispatch (cmd:'authorize', ...args: [Argument0<typeof import('./server/oidc-server/authorize.ts').default>, Argument1<typeof import('./server/oidc-server/authorize.ts').default>, Argument2<typeof import('./server/oidc-server/authorize.ts').default>, Argument3<typeof import('./server/oidc-server/authorize.ts').default>, Argument4<typeof import('./server/oidc-server/authorize.ts').default>, Argument5<typeof import('./server/oidc-server/authorize.ts').default>, Argument6<typeof import('./server/oidc-server/authorize.ts').default>, Argument7<typeof import('./server/oidc-server/authorize.ts').default>, Argument8<typeof import('./server/oidc-server/authorize.ts').default>, Argument9<typeof import('./server/oidc-server/authorize.ts').default>, Argument10<typeof import('./server/oidc-server/authorize.ts').default>, Argument11<typeof import('./server/oidc-server/authorize.ts').default>, Argument12<typeof import('./server/oidc-server/authorize.ts').default>, Argument13<typeof import('./server/oidc-server/authorize.ts').default>]): ReturnType<typeof import('./server/oidc-server/authorize.ts').default>
		dispatch (cmd:'discover', ...args: [Argument0<typeof import('./server/oidc-server/discover.ts').default>]): ReturnType<typeof import('./server/oidc-server/discover.ts').default>
		dispatch (cmd:'get-code', ...args: [Argument0<typeof import('./server/oidc-server/get-code.ts').default>, Argument1<typeof import('./server/oidc-server/get-code.ts').default>, Argument2<typeof import('./server/oidc-server/get-code.ts').default>, Argument3<typeof import('./server/oidc-server/get-code.ts').default>, Argument4<typeof import('./server/oidc-server/get-code.ts').default>, Argument5<typeof import('./server/oidc-server/get-code.ts').default>, Argument6<typeof import('./server/oidc-server/get-code.ts').default>]): ReturnType<typeof import('./server/oidc-server/get-code.ts').default>
		dispatch (cmd:'get-keys', ...args: []): ReturnType<typeof import('./server/oidc-server/get-keys.ts').default>
		dispatch (cmd:'get-token', ...args: [Argument0<typeof import('./server/oidc-server/get-token.ts').default>, Argument1<typeof import('./server/oidc-server/get-token.ts').default>, Argument2<typeof import('./server/oidc-server/get-token.ts').default>, Argument3<typeof import('./server/oidc-server/get-token.ts').default>]): ReturnType<typeof import('./server/oidc-server/get-token.ts').default>
		dispatch (cmd:'introspect', ...args: [Argument0<typeof import('./server/oidc-server/introspect.ts').default>]): ReturnType<typeof import('./server/oidc-server/introspect.ts').default>
		dispatch (cmd:'login', ...args: []): ReturnType<typeof import('./server/oidc-server/login.ts').default>
		dispatch (cmd:'remove-token', ...args: [Argument0<typeof import('./server/oidc-server/remove-token.ts').default>]): ReturnType<typeof import('./server/oidc-server/remove-token.ts').default>
		dispatch (cmd:'userinfo', ...args: [Argument0<typeof import('./server/oidc-server/userinfo.ts').default>]): ReturnType<typeof import('./server/oidc-server/userinfo.ts').default>
	}
	export interface proxy 
	{
		'authenticate'(...args: [Argument0<typeof import('./server/oidc-server/authenticate.ts').default>, Argument1<typeof import('./server/oidc-server/authenticate.ts').default>, Argument2<typeof import('./server/oidc-server/authenticate.ts').default>, Argument3<typeof import('./server/oidc-server/authenticate.ts').default>, Argument4<typeof import('./server/oidc-server/authenticate.ts').default>, Argument5<typeof import('./server/oidc-server/authenticate.ts').default>, Argument6<typeof import('./server/oidc-server/authenticate.ts').default>, Argument7<typeof import('./server/oidc-server/authenticate.ts').default>, Argument8<typeof import('./server/oidc-server/authenticate.ts').default>, Argument9<typeof import('./server/oidc-server/authenticate.ts').default>, Argument10<typeof import('./server/oidc-server/authenticate.ts').default>, Argument11<typeof import('./server/oidc-server/authenticate.ts').default>, Argument12<typeof import('./server/oidc-server/authenticate.ts').default>]): ReturnType<typeof import('./server/oidc-server/authenticate.ts').default>
		'authorize'(...args: [Argument0<typeof import('./server/oidc-server/authorize.ts').default>, Argument1<typeof import('./server/oidc-server/authorize.ts').default>, Argument2<typeof import('./server/oidc-server/authorize.ts').default>, Argument3<typeof import('./server/oidc-server/authorize.ts').default>, Argument4<typeof import('./server/oidc-server/authorize.ts').default>, Argument5<typeof import('./server/oidc-server/authorize.ts').default>, Argument6<typeof import('./server/oidc-server/authorize.ts').default>, Argument7<typeof import('./server/oidc-server/authorize.ts').default>, Argument8<typeof import('./server/oidc-server/authorize.ts').default>, Argument9<typeof import('./server/oidc-server/authorize.ts').default>, Argument10<typeof import('./server/oidc-server/authorize.ts').default>, Argument11<typeof import('./server/oidc-server/authorize.ts').default>, Argument12<typeof import('./server/oidc-server/authorize.ts').default>, Argument13<typeof import('./server/oidc-server/authorize.ts').default>]): ReturnType<typeof import('./server/oidc-server/authorize.ts').default>
		'discover'(...args: [Argument0<typeof import('./server/oidc-server/discover.ts').default>]): ReturnType<typeof import('./server/oidc-server/discover.ts').default>
		'get-code'(...args: [Argument0<typeof import('./server/oidc-server/get-code.ts').default>, Argument1<typeof import('./server/oidc-server/get-code.ts').default>, Argument2<typeof import('./server/oidc-server/get-code.ts').default>, Argument3<typeof import('./server/oidc-server/get-code.ts').default>, Argument4<typeof import('./server/oidc-server/get-code.ts').default>, Argument5<typeof import('./server/oidc-server/get-code.ts').default>, Argument6<typeof import('./server/oidc-server/get-code.ts').default>]): ReturnType<typeof import('./server/oidc-server/get-code.ts').default>
		'get-keys'(...args: []): ReturnType<typeof import('./server/oidc-server/get-keys.ts').default>
		'get-token'(...args: [Argument0<typeof import('./server/oidc-server/get-token.ts').default>, Argument1<typeof import('./server/oidc-server/get-token.ts').default>, Argument2<typeof import('./server/oidc-server/get-token.ts').default>, Argument3<typeof import('./server/oidc-server/get-token.ts').default>]): ReturnType<typeof import('./server/oidc-server/get-token.ts').default>
		'introspect'(...args: [Argument0<typeof import('./server/oidc-server/introspect.ts').default>]): ReturnType<typeof import('./server/oidc-server/introspect.ts').default>
		'login'(...args: []): ReturnType<typeof import('./server/oidc-server/login.ts').default>
		'remove-token'(...args: [Argument0<typeof import('./server/oidc-server/remove-token.ts').default>]): ReturnType<typeof import('./server/oidc-server/remove-token.ts').default>
		'userinfo'(...args: [Argument0<typeof import('./server/oidc-server/userinfo.ts').default>]): ReturnType<typeof import('./server/oidc-server/userinfo.ts').default>
	}
   export const meta={"name":"oidc-server","commands":[{"name":"authenticate","config":{"fs":{"path":"dist/esm/server/oidc-server/authenticate.js","source":"src/server/oidc-server/authenticate.ts","inject":["params.0","params.1","params.2","params.3","params.4","params.5","params.6","params.7","params.8","params.9","params.10","params.11","params.12"]},"":{"inject":["params.0","params.1","params.2","params.3","params.4","params.5","params.6","params.7","params.8","params.9","params.10","params.11","params.12"]}}},{"name":"authorize","config":{"fs":{"path":"dist/esm/server/oidc-server/authorize.js","source":"src/server/oidc-server/authorize.ts","inject":["params.0","params.1","params.2","params.3","params.4","params.5","params.6","params.7","params.8","params.9","params.10","params.11","params.12","params.13"]},"":{"inject":["params.0","params.1","params.2","params.3","params.4","params.5","params.6","params.7","params.8","params.9","params.10","params.11","params.12","params.13"]}}},{"name":"discover","config":{"fs":{"inject":["params.0","$container"],"path":"dist/esm/server/oidc-server/discover.js","source":"src/server/oidc-server/discover.ts"},"http":{"inject":["$request.uri","$container"],"method":"get","route":"/.well-known/openid-configuration","type":"json"},"":{"inject":["params.0"]}}},{"name":"get-code","config":{"fs":{"path":"dist/esm/server/oidc-server/get-code.js","source":"src/server/oidc-server/get-code.ts","inject":["params.0","params.1","params.2","params.3","params.4","params.5","params.6"]},"":{"inject":["params.0","params.1","params.2","params.3","params.4","params.5","params.6"]}}},{"name":"get-keys","config":{"fs":{"path":"dist/esm/server/oidc-server/get-keys.js","source":"src/server/oidc-server/get-keys.ts","inject":[]},"":{"inject":[]}}},{"name":"get-token","config":{"fs":{"path":"dist/esm/server/oidc-server/get-token.js","source":"src/server/oidc-server/get-token.ts","inject":["params.0","params.1","params.2","params.3"]},"":{"inject":["params.0","params.1","params.2","params.3"]}}},{"name":"introspect","config":{"fs":{"path":"dist/esm/server/oidc-server/introspect.js","source":"src/server/oidc-server/introspect.ts","inject":["params.0"]},"":{"inject":["params.0"]}}},{"name":"login","config":{"fs":{"path":"dist/esm/server/oidc-server/login.js","source":"src/server/oidc-server/login.ts","inject":[]},"":{"inject":[]}}},{"name":"remove-token","config":{"fs":{"path":"dist/esm/server/oidc-server/remove-token.js","source":"src/server/oidc-server/remove-token.ts","inject":["params.0"]},"http":{"route":"/logout","method":"post","inject":["auth.token"],"auth":{"type":"bearer"}},"":{"inject":["params.0"]}}},{"name":"userinfo","config":{"fs":{"path":"dist/esm/server/oidc-server/userinfo.js","source":"src/server/oidc-server/userinfo.ts","inject":["params.0"]},"":{"inject":["params.0"]}}}],"$schema":"https://raw.githubusercontent.com/npenin/akala/main/packages/commands/container-schema.json"} as Metadata.Container;

   export function connect(processor?:ICommandProcessor) {
            const container = new Container<void>("oidc-server", void 0);
            registerCommands(meta.commands, processor, container);
            return container as container & Container<void>;
        }
}

export { oidcServer as default };